package backendstore

// DefaultModels returns the standard seed catalog of models grouped by backend and tier.
func DefaultModels() []ModelEntry {
	nonCursor := []ModelEntry{
		// Tier 1 models
		{
			BackendID:   "claude",
			ModelID:     "opus",
			Tier:        Tier1,
			DisplayName: "Claude Opus",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "claude-opus-4-6-thinking",
			Tier:        Tier1,
			DisplayName: "Claude Opus 4.6 (Thinking)",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.1-pro-high",
			Tier:        Tier1,
			DisplayName: "Gemini 3.1 Pro (High)",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "codex",
			ModelID:     "gpt-5.5",
			Tier:        Tier1,
			DisplayName: "GPT-5.5",
			Enabled:     true,
			AutoAssign:  true,
		},

		// Tier 2 models
		{
			BackendID:   "claude",
			ModelID:     "sonnet",
			Tier:        Tier2,
			DisplayName: "Claude 3.7 Sonnet",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "claude-sonnet-4-6",
			Tier:        Tier2,
			DisplayName: "Claude Sonnet 4.6 (Thinking)",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.7-flash-high",
			Tier:        Tier2,
			DisplayName: "Gemini 3.7 Flash (High)",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.6-flash-high",
			Tier:        Tier2,
			DisplayName: "Gemini 3.6 Flash (High)",
			Enabled:     true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.1-pro-low",
			Tier:        Tier2,
			DisplayName: "Gemini 3.1 Pro (Low)",
			Enabled:     true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gpt-oss-120b-medium",
			Tier:        Tier2,
			DisplayName: "GPT-OSS 120B (Medium)",
			Enabled:     true,
		},
		{
			BackendID:   "codex",
			ModelID:     "gpt-5.6-terra",
			Tier:        Tier2,
			DisplayName: "GPT-5.6 Terra",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "codex",
			ModelID:     "gpt-5.4",
			Tier:        Tier2,
			DisplayName: "GPT-5.4",
			Enabled:     true,
		},

		// Tier 3 models
		{
			BackendID:   "claude",
			ModelID:     "haiku",
			Tier:        Tier3,
			DisplayName: "Claude 3.5 Haiku",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.7-flash-medium",
			Tier:        Tier3,
			DisplayName: "Gemini 3.7 Flash (Medium)",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.7-flash-low",
			Tier:        Tier3,
			DisplayName: "Gemini 3.7 Flash (Low)",
			Enabled:     true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.6-flash-medium",
			Tier:        Tier3,
			DisplayName: "Gemini 3.6 Flash (Medium)",
			Enabled:     true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.6-flash-low",
			Tier:        Tier3,
			DisplayName: "Gemini 3.6 Flash (Low)",
			Enabled:     true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.5-flash-high",
			Tier:        Tier3,
			DisplayName: "Gemini 3.5 Flash (High)",
			Enabled:     true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.5-flash-medium",
			Tier:        Tier3,
			DisplayName: "Gemini 3.5 Flash (Medium)",
			Enabled:     true,
		},
		{
			BackendID:   "antigravity",
			ModelID:     "gemini-3.5-flash-low",
			Tier:        Tier3,
			DisplayName: "Gemini 3.5 Flash (Low)",
			Enabled:     true,
		},
		{
			BackendID:   "codex",
			ModelID:     "gpt-5.6-luna",
			Tier:        Tier3,
			DisplayName: "GPT-5.6 Luna",
			Enabled:     true,
			AutoAssign:  true,
		},
		{
			BackendID:   "codex",
			ModelID:     "gpt-5.4-mini",
			Tier:        Tier3,
			DisplayName: "GPT-5.4 Mini",
			Enabled:     true,
		},
	}
	return append(nonCursor, cursorModels()...)
}

func cursorModels() []ModelEntry {
	return []ModelEntry{
		cursorModel("cursor-grok-4.6-high", "Cursor Grok 4.6", Tier1, false),
		cursorModel("cursor-grok-4.6-high-fast", "Cursor Grok 4.6 Fast", Tier1, true),
		cursorModel("cursor-grok-4.6-xhigh", "Cursor Grok 4.6 Extra High", Tier1, false),
		cursorModel("cursor-grok-4.6-xhigh-fast", "Cursor Grok 4.6 Extra High Fast", Tier1, false),
		cursorModel("claude-4.6-opus-high", "Claude Opus 4.6 1M", Tier1, false),
		cursorModel("claude-4.6-opus-high-thinking", "Claude Opus 4.6 1M Thinking", Tier1, false),
		cursorModel("claude-4.6-opus-max", "Claude Opus 4.6 1M Max", Tier1, false),
		cursorModel("claude-4.6-opus-max-thinking", "Claude Opus 4.6 1M Max Thinking", Tier1, false),
		cursorModel("claude-fable-5-1-thinking-high", "Claude Fable 5.1 1M Thinking (NO ZDR)", Tier1, false),
		cursorModel("claude-fable-5-1-thinking-max", "Claude Fable 5.1 1M Max Thinking (NO ZDR)", Tier1, false),
		cursorModel("claude-fable-5-1-thinking-xhigh", "Claude Fable 5.1 1M Extra High Thinking (NO ZDR)", Tier1, false),
		cursorModel("claude-fable-5-thinking-high", "Claude Fable 5 1M Thinking (NO ZDR)", Tier1, false),
		cursorModel("claude-fable-5-thinking-max", "Claude Fable 5 1M Max Thinking (NO ZDR)", Tier1, false),
		cursorModel("claude-fable-5-thinking-xhigh", "Claude Fable 5 1M Extra High Thinking (NO ZDR)", Tier1, false),
		cursorModel("claude-opus-4-7-high", "Claude Opus 4.7 1M High", Tier1, false),
		cursorModel("claude-opus-4-7-high-fast", "Claude Opus 4.7 1M High Fast", Tier1, false),
		cursorModel("claude-opus-4-7-max", "Claude Opus 4.7 1M Max", Tier1, false),
		cursorModel("claude-opus-4-7-max-fast", "Claude Opus 4.7 1M Max Fast", Tier1, false),
		cursorModel("claude-opus-4-7-thinking-high", "Claude Opus 4.7 1M High Thinking", Tier1, false),
		cursorModel("claude-opus-4-7-thinking-high-fast", "Claude Opus 4.7 1M High Thinking Fast", Tier1, false),
		cursorModel("claude-opus-4-7-thinking-max", "Claude Opus 4.7 1M Max Thinking", Tier1, false),
		cursorModel("claude-opus-4-7-thinking-max-fast", "Claude Opus 4.7 1M Max Thinking Fast", Tier1, false),
		cursorModel("claude-opus-4-7-thinking-xhigh", "Claude Opus 4.7 1M Thinking", Tier1, false),
		cursorModel("claude-opus-4-7-thinking-xhigh-fast", "Claude Opus 4.7 1M Thinking Fast", Tier1, false),
		cursorModel("claude-opus-4-7-xhigh", "Claude Opus 4.7 1M", Tier1, false),
		cursorModel("claude-opus-4-7-xhigh-fast", "Claude Opus 4.7 1M Fast", Tier1, false),
		cursorModel("claude-opus-4-8-high", "Claude Opus 4.8 1M", Tier1, false),
		cursorModel("claude-opus-4-8-high-fast", "Claude Opus 4.8 1M Fast", Tier1, false),
		cursorModel("claude-opus-4-8-max", "Claude Opus 4.8 1M Max", Tier1, false),
		cursorModel("claude-opus-4-8-max-fast", "Claude Opus 4.8 1M Max Fast", Tier1, false),
		cursorModel("claude-opus-4-8-thinking-high", "Claude Opus 4.8 1M Thinking", Tier1, false),
		cursorModel("claude-opus-4-8-thinking-high-fast", "Claude Opus 4.8 1M Thinking Fast", Tier1, false),
		cursorModel("claude-opus-4-8-thinking-max", "Claude Opus 4.8 1M Max Thinking", Tier1, false),
		cursorModel("claude-opus-4-8-thinking-max-fast", "Claude Opus 4.8 1M Max Thinking Fast", Tier1, false),
		cursorModel("claude-opus-4-8-thinking-xhigh", "Claude Opus 4.8 1M Extra High Thinking", Tier1, false),
		cursorModel("claude-opus-4-8-thinking-xhigh-fast", "Claude Opus 4.8 1M Extra High Thinking Fast", Tier1, false),
		cursorModel("claude-opus-4-8-xhigh", "Claude Opus 4.8 1M Extra High", Tier1, false),
		cursorModel("claude-opus-4-8-xhigh-fast", "Claude Opus 4.8 1M Extra High Fast", Tier1, false),
		cursorModel("claude-opus-5-high", "Claude Opus 5 1M", Tier1, false),
		cursorModel("claude-opus-5-high-fast", "Claude Opus 5 1M Fast", Tier1, false),
		cursorModel("claude-opus-5-thinking-high", "Claude Opus 5 1M Thinking", Tier1, true),
		cursorModel("claude-opus-5-thinking-high-fast", "Claude Opus 5 1M Thinking Fast", Tier1, false),
		cursorModel("claude-opus-5-thinking-max", "Claude Opus 5 1M Max Thinking", Tier1, false),
		cursorModel("claude-opus-5-thinking-max-fast", "Claude Opus 5 1M Max Thinking Fast", Tier1, false),
		cursorModel("claude-opus-5-thinking-xhigh", "Claude Opus 5 1M Extra High Thinking", Tier1, false),
		cursorModel("claude-opus-5-thinking-xhigh-fast", "Claude Opus 5 1M Extra High Thinking Fast", Tier1, false),
		cursorModel("gpt-5.3-codex-xhigh", "Codex 5.3 Extra High", Tier1, false),
		cursorModel("gpt-5.3-codex-xhigh-fast", "Codex 5.3 Extra High Fast", Tier1, false),
		cursorModel("gpt-5.5-extra-high", "GPT-5.5 1M Extra High", Tier1, false),
		cursorModel("gpt-5.5-extra-high-fast", "GPT-5.5 Extra High Fast", Tier1, false),
		cursorModel("gpt-5.6-sol-max", "GPT-5.6 Sol 1M Max", Tier1, false),
		cursorModel("gpt-5.6-sol-max-fast", "GPT-5.6 Sol Max Fast", Tier1, false),
		cursorModel("gpt-5.6-sol-xhigh", "GPT-5.6 Sol 1M Extra High", Tier1, false),
		cursorModel("gpt-5.6-sol-xhigh-fast", "GPT-5.6 Sol Extra High Fast", Tier1, false),
		cursorModel("composer-2.5", "Composer 2.5", Tier2, false),
		cursorModel("cursor-grok-4.5-high", "Cursor Grok 4.5", Tier2, true),
		cursorModel("cursor-grok-4.5-high-fast", "Cursor Grok 4.5 Fast", Tier2, false),
		cursorModel("cursor-grok-4.5-medium", "Cursor Grok 4.5 Medium", Tier2, false),
		cursorModel("cursor-grok-4.5-medium-fast", "Cursor Grok 4.5 Medium Fast", Tier2, false),
		cursorModel("cursor-grok-4.6-medium", "Cursor Grok 4.6 Medium", Tier2, false),
		cursorModel("cursor-grok-4.6-medium-fast", "Cursor Grok 4.6 Medium Fast", Tier2, false),
		cursorModel("auto", "Auto (default)", Tier2, true),
		cursorModel("claude-4-sonnet", "Claude Sonnet 4", Tier2, false),
		cursorModel("claude-4-sonnet-thinking", "Claude Sonnet 4 Thinking", Tier2, false),
		cursorModel("claude-4.5-opus-high", "Claude Opus 4.5", Tier2, false),
		cursorModel("claude-4.5-opus-high-thinking", "Claude Opus 4.5 Thinking", Tier2, false),
		cursorModel("claude-4.5-sonnet", "Claude Sonnet 4.5", Tier2, false),
		cursorModel("claude-4.5-sonnet-thinking", "Claude Sonnet 4.5 Thinking", Tier2, false),
		cursorModel("claude-4.6-sonnet-medium", "Claude Sonnet 4.6 1M", Tier2, false),
		cursorModel("claude-4.6-sonnet-medium-thinking", "Claude Sonnet 4.6 1M Thinking", Tier2, false),
		cursorModel("claude-fable-5-1-high", "Claude Fable 5.1 1M (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-1-low", "Claude Fable 5.1 1M Low (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-1-max", "Claude Fable 5.1 1M Max (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-1-medium", "Claude Fable 5.1 1M Medium (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-1-thinking-low", "Claude Fable 5.1 1M Low Thinking (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-1-thinking-medium", "Claude Fable 5.1 1M Medium Thinking (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-1-xhigh", "Claude Fable 5.1 1M Extra High (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-high", "Claude Fable 5 1M (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-low", "Claude Fable 5 1M Low (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-max", "Claude Fable 5 1M Max (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-medium", "Claude Fable 5 1M Medium (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-thinking-low", "Claude Fable 5 1M Low Thinking (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-thinking-medium", "Claude Fable 5 1M Medium Thinking (NO ZDR)", Tier2, false),
		cursorModel("claude-fable-5-xhigh", "Claude Fable 5 1M Extra High (NO ZDR)", Tier2, false),
		cursorModel("claude-opus-4-7-low", "Claude Opus 4.7 1M Low", Tier2, false),
		cursorModel("claude-opus-4-7-low-fast", "Claude Opus 4.7 1M Low Fast", Tier2, false),
		cursorModel("claude-opus-4-7-medium", "Claude Opus 4.7 1M Medium", Tier2, false),
		cursorModel("claude-opus-4-7-medium-fast", "Claude Opus 4.7 1M Medium Fast", Tier2, false),
		cursorModel("claude-opus-4-7-thinking-low", "Claude Opus 4.7 1M Low Thinking", Tier2, false),
		cursorModel("claude-opus-4-7-thinking-low-fast", "Claude Opus 4.7 1M Low Thinking Fast", Tier2, false),
		cursorModel("claude-opus-4-7-thinking-medium", "Claude Opus 4.7 1M Medium Thinking", Tier2, false),
		cursorModel("claude-opus-4-7-thinking-medium-fast", "Claude Opus 4.7 1M Medium Thinking Fast", Tier2, false),
		cursorModel("claude-opus-4-8-low", "Claude Opus 4.8 1M Low", Tier2, false),
		cursorModel("claude-opus-4-8-low-fast", "Claude Opus 4.8 1M Low Fast", Tier2, false),
		cursorModel("claude-opus-4-8-medium", "Claude Opus 4.8 1M Medium", Tier2, false),
		cursorModel("claude-opus-4-8-medium-fast", "Claude Opus 4.8 1M Medium Fast", Tier2, false),
		cursorModel("claude-opus-4-8-thinking-low", "Claude Opus 4.8 1M Low Thinking", Tier2, false),
		cursorModel("claude-opus-4-8-thinking-low-fast", "Claude Opus 4.8 1M Low Thinking Fast", Tier2, false),
		cursorModel("claude-opus-4-8-thinking-medium", "Claude Opus 4.8 1M Medium Thinking", Tier2, false),
		cursorModel("claude-opus-4-8-thinking-medium-fast", "Claude Opus 4.8 1M Medium Thinking Fast", Tier2, false),
		cursorModel("claude-opus-5-low", "Claude Opus 5 1M Low", Tier2, false),
		cursorModel("claude-opus-5-low-fast", "Claude Opus 5 1M Low Fast", Tier2, false),
		cursorModel("claude-opus-5-medium", "Claude Opus 5 1M Medium", Tier2, false),
		cursorModel("claude-opus-5-medium-fast", "Claude Opus 5 1M Medium Fast", Tier2, false),
		cursorModel("claude-opus-5-thinking-low", "Claude Opus 5 1M Low Thinking", Tier2, false),
		cursorModel("claude-opus-5-thinking-low-fast", "Claude Opus 5 1M Low Thinking Fast", Tier2, false),
		cursorModel("claude-opus-5-thinking-medium", "Claude Opus 5 1M Medium Thinking", Tier2, false),
		cursorModel("claude-opus-5-thinking-medium-fast", "Claude Opus 5 1M Medium Thinking Fast", Tier2, false),
		cursorModel("claude-sonnet-5-high", "Claude Sonnet 5 1M", Tier2, false),
		cursorModel("claude-sonnet-5-low", "Claude Sonnet 5 1M Low", Tier2, false),
		cursorModel("claude-sonnet-5-max", "Claude Sonnet 5 1M Max", Tier2, false),
		cursorModel("claude-sonnet-5-medium", "Claude Sonnet 5 1M Medium", Tier2, false),
		cursorModel("claude-sonnet-5-thinking-high", "Claude Sonnet 5 1M Thinking", Tier2, true),
		cursorModel("claude-sonnet-5-thinking-low", "Claude Sonnet 5 1M Low Thinking", Tier2, false),
		cursorModel("claude-sonnet-5-thinking-max", "Claude Sonnet 5 1M Max Thinking", Tier2, false),
		cursorModel("claude-sonnet-5-thinking-medium", "Claude Sonnet 5 1M Medium Thinking", Tier2, false),
		cursorModel("claude-sonnet-5-thinking-xhigh", "Claude Sonnet 5 1M Extra High Thinking", Tier2, false),
		cursorModel("claude-sonnet-5-xhigh", "Claude Sonnet 5 1M Extra High", Tier2, false),
		cursorModel("gemini-3.1-pro", "Gemini 3.1 Pro", Tier2, false),
		cursorModel("gpt-5.2", "GPT-5.2", Tier2, false),
		cursorModel("gpt-5.2-fast", "GPT-5.2 Fast", Tier2, false),
		cursorModel("gpt-5.2-high", "GPT-5.2 High", Tier2, false),
		cursorModel("gpt-5.2-high-fast", "GPT-5.2 High Fast", Tier2, false),
		cursorModel("gpt-5.2-low", "GPT-5.2 Low", Tier2, false),
		cursorModel("gpt-5.2-low-fast", "GPT-5.2 Low Fast", Tier2, false),
		cursorModel("gpt-5.2-xhigh", "GPT-5.2 Extra High", Tier2, false),
		cursorModel("gpt-5.2-xhigh-fast", "GPT-5.2 Extra High Fast", Tier2, false),
		cursorModel("gpt-5.3-codex", "Codex 5.3", Tier2, false),
		cursorModel("gpt-5.3-codex-fast", "Codex 5.3 Fast", Tier2, false),
		cursorModel("gpt-5.3-codex-high", "Codex 5.3 High", Tier2, false),
		cursorModel("gpt-5.3-codex-high-fast", "Codex 5.3 High Fast", Tier2, false),
		cursorModel("gpt-5.4-high", "GPT-5.4 1M High", Tier2, false),
		cursorModel("gpt-5.4-high-fast", "GPT-5.4 High Fast", Tier2, false),
		cursorModel("gpt-5.4-low", "GPT-5.4 1M Low", Tier2, false),
		cursorModel("gpt-5.4-medium", "GPT-5.4 1M", Tier2, false),
		cursorModel("gpt-5.4-medium-fast", "GPT-5.4 Fast", Tier2, false),
		cursorModel("gpt-5.4-xhigh", "GPT-5.4 1M Extra High", Tier2, false),
		cursorModel("gpt-5.4-xhigh-fast", "GPT-5.4 Extra High Fast", Tier2, false),
		cursorModel("gpt-5.5-high", "GPT-5.5 1M High", Tier2, false),
		cursorModel("gpt-5.5-high-fast", "GPT-5.5 High Fast", Tier2, false),
		cursorModel("gpt-5.5-low", "GPT-5.5 1M Low", Tier2, false),
		cursorModel("gpt-5.5-low-fast", "GPT-5.5 Low Fast", Tier2, false),
		cursorModel("gpt-5.5-medium", "GPT-5.5 1M", Tier2, false),
		cursorModel("gpt-5.5-medium-fast", "GPT-5.5 Fast", Tier2, false),
		cursorModel("gpt-5.5-none", "GPT-5.5 1M None", Tier2, false),
		cursorModel("gpt-5.5-none-fast", "GPT-5.5 None Fast", Tier2, false),
		cursorModel("gpt-5.6-luna-high", "GPT-5.6 Luna 1M High", Tier2, false),
		cursorModel("gpt-5.6-luna-high-fast", "GPT-5.6 Luna High Fast", Tier2, false),
		cursorModel("gpt-5.6-luna-low", "GPT-5.6 Luna 1M Low", Tier2, false),
		cursorModel("gpt-5.6-luna-low-fast", "GPT-5.6 Luna Low Fast", Tier2, false),
		cursorModel("gpt-5.6-luna-max", "GPT-5.6 Luna 1M Max", Tier2, false),
		cursorModel("gpt-5.6-luna-max-fast", "GPT-5.6 Luna Max Fast", Tier2, false),
		cursorModel("gpt-5.6-luna-medium", "GPT-5.6 Luna 1M", Tier2, false),
		cursorModel("gpt-5.6-luna-medium-fast", "GPT-5.6 Luna Fast", Tier2, false),
		cursorModel("gpt-5.6-luna-none", "GPT-5.6 Luna 1M None", Tier2, false),
		cursorModel("gpt-5.6-luna-none-fast", "GPT-5.6 Luna None Fast", Tier2, false),
		cursorModel("gpt-5.6-luna-xhigh", "GPT-5.6 Luna 1M Extra High", Tier2, false),
		cursorModel("gpt-5.6-luna-xhigh-fast", "GPT-5.6 Luna Extra High Fast", Tier2, false),
		cursorModel("gpt-5.6-sol-high", "GPT-5.6 Sol 1M High", Tier2, false),
		cursorModel("gpt-5.6-sol-high-fast", "GPT-5.6 Sol High Fast", Tier2, false),
		cursorModel("gpt-5.6-sol-low", "GPT-5.6 Sol 1M Low", Tier2, false),
		cursorModel("gpt-5.6-sol-low-fast", "GPT-5.6 Sol Low Fast", Tier2, false),
		cursorModel("gpt-5.6-sol-medium", "GPT-5.6 Sol 1M", Tier2, false),
		cursorModel("gpt-5.6-sol-medium-fast", "GPT-5.6 Sol Fast", Tier2, false),
		cursorModel("gpt-5.6-sol-none", "GPT-5.6 Sol 1M None", Tier2, false),
		cursorModel("gpt-5.6-sol-none-fast", "GPT-5.6 Sol None Fast", Tier2, false),
		cursorModel("gpt-5.6-terra-high", "GPT-5.6 Terra 1M High", Tier2, false),
		cursorModel("gpt-5.6-terra-high-fast", "GPT-5.6 Terra High Fast", Tier2, false),
		cursorModel("gpt-5.6-terra-low", "GPT-5.6 Terra 1M Low", Tier2, false),
		cursorModel("gpt-5.6-terra-low-fast", "GPT-5.6 Terra Low Fast", Tier2, false),
		cursorModel("gpt-5.6-terra-max", "GPT-5.6 Terra 1M Max", Tier2, false),
		cursorModel("gpt-5.6-terra-max-fast", "GPT-5.6 Terra Max Fast", Tier2, false),
		cursorModel("gpt-5.6-terra-medium", "GPT-5.6 Terra 1M", Tier2, false),
		cursorModel("gpt-5.6-terra-medium-fast", "GPT-5.6 Terra Fast", Tier2, false),
		cursorModel("gpt-5.6-terra-none", "GPT-5.6 Terra 1M None", Tier2, false),
		cursorModel("gpt-5.6-terra-none-fast", "GPT-5.6 Terra None Fast", Tier2, false),
		cursorModel("gpt-5.6-terra-xhigh", "GPT-5.6 Terra 1M Extra High", Tier2, false),
		cursorModel("gpt-5.6-terra-xhigh-fast", "GPT-5.6 Terra Extra High Fast", Tier2, false),
		cursorModel("composer-2.5-fast", "Composer 2.5 Fast", Tier3, true),
		cursorModel("cursor-grok-4.5-low", "Cursor Grok 4.5 Low", Tier3, false),
		cursorModel("cursor-grok-4.5-low-fast", "Cursor Grok 4.5 Low Fast", Tier3, false),
		cursorModel("cursor-grok-4.6-low", "Cursor Grok 4.6 Low", Tier3, false),
		cursorModel("cursor-grok-4.6-low-fast", "Cursor Grok 4.6 Low Fast", Tier3, false),
		cursorModel("gemini-3-flash", "Gemini 3 Flash", Tier3, false),
		cursorModel("gemini-3.5-flash", "Gemini 3.5 Flash", Tier3, false),
		cursorModel("gemini-3.6-flash-high", "Gemini 3.6 Flash", Tier3, false),
		cursorModel("gemini-3.6-flash-low", "Gemini 3.6 Flash Low", Tier3, false),
		cursorModel("gemini-3.6-flash-medium", "Gemini 3.6 Flash Medium", Tier3, false),
		cursorModel("gemini-3.6-flash-minimal", "Gemini 3.6 Flash Minimal", Tier3, false),
		cursorModel("gemini-3.7-flash-high", "Gemini 3.7 Flash", Tier3, true),
		cursorModel("gemini-3.7-flash-low", "Gemini 3.7 Flash Low", Tier3, false),
		cursorModel("gemini-3.7-flash-medium", "Gemini 3.7 Flash Medium", Tier3, false),
		cursorModel("glm-5.2-high", "GLM 5.2", Tier3, false),
		cursorModel("glm-5.2-max", "GLM 5.2 Max", Tier3, false),
		cursorModel("gpt-5-mini", "GPT-5 Mini", Tier3, false),
		cursorModel("gpt-5.1", "GPT-5.1", Tier3, false),
		cursorModel("gpt-5.1-high", "GPT-5.1 High", Tier3, false),
		cursorModel("gpt-5.1-low", "GPT-5.1 Low", Tier3, false),
		cursorModel("gpt-5.3-codex-low", "Codex 5.3 Low", Tier3, false),
		cursorModel("gpt-5.3-codex-low-fast", "Codex 5.3 Low Fast", Tier3, false),
		cursorModel("gpt-5.4-mini-high", "GPT-5.4 Mini High", Tier3, false),
		cursorModel("gpt-5.4-mini-low", "GPT-5.4 Mini Low", Tier3, false),
		cursorModel("gpt-5.4-mini-medium", "GPT-5.4 Mini", Tier3, false),
		cursorModel("gpt-5.4-mini-none", "GPT-5.4 Mini None", Tier3, false),
		cursorModel("gpt-5.4-mini-xhigh", "GPT-5.4 Mini Extra High", Tier3, false),
		cursorModel("gpt-5.4-nano-high", "GPT-5.4 Nano High", Tier3, false),
		cursorModel("gpt-5.4-nano-low", "GPT-5.4 Nano Low", Tier3, false),
		cursorModel("gpt-5.4-nano-medium", "GPT-5.4 Nano", Tier3, false),
		cursorModel("gpt-5.4-nano-none", "GPT-5.4 Nano None", Tier3, false),
		cursorModel("gpt-5.4-nano-xhigh", "GPT-5.4 Nano Extra High", Tier3, false),
		cursorModel("kimi-k2.7-code", "Kimi K2.7 Code", Tier3, false),
		cursorModel("kimi-k3-high", "Kimi K3 High", Tier3, false),
		cursorModel("kimi-k3-low", "Kimi K3 Low", Tier3, false),
		cursorModel("kimi-k3-max", "Kimi K3", Tier3, false),
	}
}

func cursorModel(id, display string, tier ModelTier, autoAssign bool) ModelEntry {
	return ModelEntry{
		BackendID:   "cursor",
		ModelID:     id,
		Tier:        tier,
		DisplayName: display,
		Enabled:     true,
		AutoAssign:  autoAssign,
	}
}

// DefaultRoleTiers returns the default mapping of agent ROLES to model tiers,
// keyed by the actual role names defined under internal/role/roles/*.yaml.
//
// These feed GetRoleTier(role), which the router consults as the Role tier in
// its precedence chain (explicit tier > task tier > role tier > Tier2 default).
// Task-to-tier mappings do NOT live here — internal/task (task.TierFor) is the
// single canonical source for that. A role without an explicit entry here falls
// through to Tier2 in the resolver.
//
// Migration note: earlier builds mis-seeded this collection with TASK-like keys
// (analysis, architecture, planning, design, arch-design-review, autopilot,
// pr-review, implementation, debugger, code-review, ci-triage). Seeding is
// idempotent and never deletes existing keys, so those stale keys survive in
// already-seeded stores but are simply dead: nothing queries role_tiers by task
// name once tasks route through task.TierFor. They cause no runtime breakage.
func DefaultRoleTiers() []RoleTierMapping {
	return []RoleTierMapping{
		{RoleName: "general", DefaultTier: Tier2},
		{RoleName: "orchestrator", DefaultTier: Tier1},
		{RoleName: "planner", DefaultTier: Tier1},
		{RoleName: "worker", DefaultTier: Tier2},
		{RoleName: "autopilot", DefaultTier: Tier1},
		{RoleName: "brain", DefaultTier: Tier2},
	}
}
