package cli

import (
	"bytes"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

// referenceHeader is the fixed frontmatter + preamble prepended to the generated
// CLI reference. It mirrors the intro of the old hand-written page so the tone
// and the "how to read a TICKET" note survive the switch to generation.
const referenceHeader = `---
title: CLI command reference
description: Every warden command and its flags, generated from the cobra command tree.
---

{/* Code-generated by cmd/gendocs from the warden cobra command tree. DO NOT EDIT.
    Regenerate with ` + "`make gendocs`" + ` after changing any command's Use/Short/Long
    or flags; CI (` + "`make gendocs-check`" + `) fails the build if this file is stale. */}

Every ` + "`warden`" + ` command and its flags, walked straight from the live cobra
command tree, so this page can never drift from the actual ` + "`--help`" + ` output.

All commands accept ` + "`--addr`" + ` to point at a non-default daemon (overrides the
` + "`addr`" + ` config setting) and ` + "`--config`" + ` to point at a non-default config file
(default ` + "`~/.warden/config.yaml`" + `). ` + "`<TICKET>`" + ` is the agent ID — a Jira key
for managed agents, or an ` + "`agent-xxxx`" + ` ID for prompt-spawned ones.
`

// GenerateReference walks the real warden cobra command tree and renders a
// Markdown reference page: one section per (visible) command carrying that
// command's exact `--help` output. It is the single source of truth behind
// site/src/content/docs/reference/cli.md — see cmd/gendocs.
//
// Because the text comes from the same *cobra.Command tree the binary runs,
// the page cannot drift from real `--help`; the CI staleness gate
// (`make gendocs-check`) enforces that the committed copy is regenerated.
func GenerateReference() (string, error) {
	root := newRootCmd()

	// Help() renders to the command's out writer; point the whole tree at one
	// buffer (children inherit the root's writer) and reset it per command.
	var out bytes.Buffer
	root.SetOut(&out)
	root.SetErr(&out)

	var b strings.Builder
	b.WriteString(referenceHeader)

	var walk func(c *cobra.Command) error
	walk = func(c *cobra.Command) error {
		// Cobra only wires the default `-h/--help` (and root's `-v/--version`)
		// flags during Execute(); do it explicitly so the rendered help matches
		// what a user actually sees from `warden <cmd> --help`.
		c.InitDefaultHelpFlag()
		c.InitDefaultVersionFlag()

		out.Reset()
		if err := c.Help(); err != nil {
			return err
		}
		help := out.String()
		// The root's Long embeds the ASCII wordmark; strip it so the reference
		// leads with the description, not the banner.
		help = strings.Replace(help, banner+"\n\n", "", 1)
		help = strings.TrimRight(help, "\n")

		b.WriteString("\n## ")
		b.WriteString(c.CommandPath())
		b.WriteString("\n\n```text\n")
		b.WriteString(help)
		b.WriteString("\n```\n")

		children := append([]*cobra.Command(nil), c.Commands()...)
		sortCommands(children)
		for _, sub := range children {
			// Skip the auto-generated `help` command and any hidden or
			// help-topic-only commands — they are not user-facing verbs.
			if sub.Hidden || sub.IsAdditionalHelpTopicCommand() || sub.Name() == "help" || sub.Annotations[AnnotationIncludeInDocs] == "false" {
				continue
			}
			if err := walk(sub); err != nil {
				return err
			}
		}
		return nil
	}
	if err := walk(root); err != nil {
		return "", err
	}
	writeAliasAppendix(&b, root)

	doc := b.String()
	// Some help text bakes in an absolute path resolved from $HOME at command
	// construction (e.g. `warden token`'s default token file). Rewrite the home
	// prefix to `~` so the generated page is byte-identical across machines —
	// otherwise the CI staleness gate would flip on every contributor's home dir.
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		doc = strings.ReplaceAll(doc, home, "~")
	}
	return doc, nil
}

func writeAliasAppendix(b *strings.Builder, root *cobra.Command) {
	aliases := CollectCompatibilityAliases(root)
	if len(aliases) == 0 {
		return
	}
	b.WriteString("\n## Compatibility aliases\n\n")
	b.WriteString("Every path below predates the command redesign and still runs, dispatching the\n")
	b.WriteString("same option parsing and run logic as its canonical path. They are hidden from\n")
	b.WriteString("normal help and completion; `warden help --all` lists the same set. Nothing here\n")
	b.WriteString("is scheduled for removal — prefer the canonical path in new scripts and docs.\n\n")
	b.WriteString("| Legacy path | Canonical path |\n|---|---|\n")
	for _, alias := range aliases {
		canonical := "`" + alias.Canonical + "`"
		if alias.Retained() {
			canonical = "_retained; no canonical equivalent_"
		}
		b.WriteString("| `" + alias.Path + "` | " + canonical + " |\n")
	}
}
