package digest

import (
	"fmt"
	"strings"
)

// Markdown renders a digest as a GitHub-flavored PR body: the summary narrative,
// a changed-files table with +/- line counts, and a generated-by footer. Shared
// by the `done --create-pr` flow so the PR body is the same digest the CLI, web,
// and TUI already show. Returns just the footer when there is nothing to report.
func Markdown(d *Digest) string {
	var b strings.Builder
	if s := strings.TrimSpace(d.Summary); s != "" {
		b.WriteString(s)
		b.WriteString("\n\n")
	}
	if len(d.Files) > 0 {
		b.WriteString("## Changed files\n\n")
		b.WriteString("| File | +added | −removed |\n| --- | --- | --- |\n")
		for _, f := range d.Files {
			fmt.Fprintf(&b, "| `%s` | %d | %d |\n", f.Path, f.Added, f.Removed)
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n🤖 Generated by a [warden](https://github.com/srjn45/warden) agent")
	return b.String()
}
