package digest

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestMarkdownRendersSummaryFilesAndFooter(t *testing.T) {
	d := &Digest{
		Summary: "Added a widget and wired it up.",
		Files: []FileChange{
			{Path: "internal/a.go", Added: 10, Removed: 2},
			{Path: "internal/b.go", Added: 1, Removed: 0},
		},
	}
	md := Markdown(d)
	require.Contains(t, md, "Added a widget and wired it up.")
	require.Contains(t, md, "## Changed files")
	require.Contains(t, md, "| `internal/a.go` | 10 | 2 |")
	require.Contains(t, md, "| `internal/b.go` | 1 | 0 |")
	require.Contains(t, md, "Generated by")
}

func TestMarkdownOmitsEmptySections(t *testing.T) {
	md := Markdown(&Digest{})
	require.NotContains(t, md, "## Changed files")
	require.False(t, strings.HasPrefix(md, "\n"), "no leading blank line when summary is empty")
	require.Contains(t, md, "Generated by")
}
