#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.md from the module graph of the warden binary.
#
# Deterministic by design (sorted, no timestamp) so CI can regenerate and diff it
# against the committed copy to catch a stale notices file when dependencies
# change. Requires google/go-licenses on PATH:
#   go install github.com/google/go-licenses@latest
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v go-licenses >/dev/null 2>&1; then
  echo "gen-notices: go-licenses not found on PATH" >&2
  echo "  install: go install github.com/google/go-licenses@latest" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# csv columns: module,license-url,license-id. Sorted for a stable diff; the
# warden module itself (empty version → HEAD) is dropped below. LC_ALL=C pins a
# byte-wise sort so the order is identical on every machine (a locale that folds
# punctuation would, e.g., order `go.yaml.in/...` differently from CI).
go-licenses csv ./cmd/warden 2>/dev/null | LC_ALL=C sort >"$tmp"

{
  echo "# Third-Party Notices"
  echo
  echo "warden (Apache-2.0) is built with the open-source Go modules listed below."
  echo "All are permissive licenses (Apache-2.0, MIT, BSD-3-Clause, ISC) — no copyleft"
  echo "(GPL/LGPL/AGPL) dependencies. Each project is the copyright of its respective"
  echo "authors; follow the linked license for the full text and notices."
  echo
  echo "_Generated by \`scripts/gen-notices.sh\` (google/go-licenses). Regenerate and"
  echo "commit whenever dependencies change; CI fails if this file is stale._"
  echo
  echo "| Module | License | Text |"
  echo "|--------|---------|------|"
  grep -v '^github.com/srjn45/warden,' "$tmp" \
    | awk -F, '{printf "| `%s` | %s | [link](%s) |\n", $1, $3, $2}'
} >THIRD-PARTY-NOTICES.md

echo "gen-notices: wrote THIRD-PARTY-NOTICES.md ($(grep -c '^| `' THIRD-PARTY-NOTICES.md) modules)"
