package handoff

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// wardenDir is the per-worktree directory warden writes the handoff file into. It
// mirrors the convention used by .warden/memory.md and .warden/check.yml, so a
// successor agent finds all warden-managed context in one place.
const wardenDir = ".warden"

// Filename returns the handoff file's basename for a session id —
// `handoff-<session-id>.md`. The id is sanitized so a stray path separator can never
// escape the .warden directory (defense in depth; warden ids are already opaque).
func Filename(sessionID string) string {
	return "handoff-" + sanitizeID(sessionID) + ".md"
}

// Path returns the absolute path of the handoff file for a session inside worktree:
// `<worktree>/.warden/handoff-<session-id>.md`.
func Path(worktree, sessionID string) string {
	return filepath.Join(worktree, wardenDir, Filename(sessionID))
}

// Write renders h to markdown and writes it to `<worktree>/.warden/handoff-<id>.md`,
// creating the .warden directory if needed. It returns the path written so the
// caller can reference it in the successor's launch prompt. h.SessionID names the
// file, so it must be set. A worktree of "" is an error — there is nowhere to write.
func Write(worktree string, h Handoff) (string, error) {
	if strings.TrimSpace(worktree) == "" {
		return "", fmt.Errorf("handoff: empty worktree")
	}
	if strings.TrimSpace(h.SessionID) == "" {
		return "", fmt.Errorf("handoff: empty session id")
	}
	dir := filepath.Join(worktree, wardenDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("handoff: create %s: %w", dir, err)
	}
	path := filepath.Join(dir, Filename(h.SessionID))
	if err := os.WriteFile(path, []byte(h.Markdown()), 0o644); err != nil {
		return "", fmt.Errorf("handoff: write %s: %w", path, err)
	}
	return path, nil
}

// Markdown renders the handoff as a structured markdown document with the sections a
// successor backend reads to continue the work: Goal, Decisions Log, Modified Files,
// Immediate Next Step, and System Context. Every section is always present; an empty
// field renders as an explicit placeholder so the successor can tell "nothing to
// report" from a truncated file.
func (h Handoff) Markdown() string {
	var b strings.Builder

	title := h.SessionID
	if title == "" {
		title = "session"
	}
	fmt.Fprintf(&b, "# Warden Session Handoff — %s\n\n", title)

	b.WriteString("> Auto-generated by warden's mid-session hot-swap engine. ")
	b.WriteString("You are the SUCCESSOR agent picking up an in-progress session. ")
	b.WriteString("Read this handoff, then continue the work from the Immediate Next Step below.\n\n")

	writeMeta(&b, h)

	b.WriteString("## Goal\n\n")
	b.WriteString(orPlaceholder(h.Goal, "_No explicit goal was recorded in the transcript._"))
	b.WriteString("\n\n")

	b.WriteString("## Decisions Log\n\n")
	if len(h.Decisions) == 0 {
		b.WriteString("_No notable decisions were recorded._\n\n")
	} else {
		for _, d := range h.Decisions {
			fmt.Fprintf(&b, "- %s\n", d)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Modified Files\n\n")
	if len(h.ModifiedFiles) == 0 {
		b.WriteString("_No file modifications were recorded in the transcript._\n\n")
	} else {
		for _, f := range h.ModifiedFiles {
			fmt.Fprintf(&b, "- `%s`\n", f)
		}
		b.WriteString("\n")
	}

	if strings.TrimSpace(h.GitDiff) != "" {
		b.WriteString("### Working-tree diff (numstat)\n\n")
		b.WriteString("```\n")
		b.WriteString(strings.TrimRight(h.GitDiff, "\n"))
		b.WriteString("\n```\n\n")
	}

	b.WriteString("## Immediate Next Step\n\n")
	b.WriteString(orPlaceholder(h.NextStep, "_No explicit next step was recorded — review the Goal and Modified Files, then continue._"))
	b.WriteString("\n\n")

	b.WriteString("## System Context\n\n")
	b.WriteString(orPlaceholder(h.SystemContext, "_No additional system context was provided._"))
	b.WriteString("\n")

	return b.String()
}

// writeMeta renders the provenance block (who handed off to whom, and why) when any
// of it is set. It is a compact bullet list rather than a section so it sits just
// under the banner as orienting metadata.
func writeMeta(b *strings.Builder, h Handoff) {
	var rows [][2]string
	if h.Backend != "" {
		from := h.Backend
		if h.Model != "" {
			from += " (" + h.Model + ")"
		}
		rows = append(rows, [2]string{"Retired backend", from})
	}
	if h.SuccessorBackend != "" {
		to := h.SuccessorBackend
		if h.SuccessorModel != "" {
			to += " (" + h.SuccessorModel + ")"
		}
		rows = append(rows, [2]string{"Successor backend", to})
	}
	if h.Reason != "" {
		rows = append(rows, [2]string{"Swap reason", h.Reason})
	}
	if h.GeneratedAt != "" {
		rows = append(rows, [2]string{"Generated at", h.GeneratedAt})
	}
	if len(rows) == 0 {
		return
	}
	for _, r := range rows {
		fmt.Fprintf(b, "- **%s:** %s\n", r[0], r[1])
	}
	b.WriteString("\n")
}

// orPlaceholder returns s trimmed, or the placeholder when s is blank.
func orPlaceholder(s, placeholder string) string {
	if strings.TrimSpace(s) == "" {
		return placeholder
	}
	return strings.TrimRight(s, "\n")
}

// sanitizeID reduces a session id to a filesystem-safe token: it keeps
// alphanumerics, dash, and underscore, and replaces everything else (including path
// separators) with a dash. An id that reduces to empty becomes "session" so the file
// always has a stable name.
func sanitizeID(id string) string {
	var b strings.Builder
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "session"
	}
	return out
}
