package daemon

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"github.com/srjn45/warden/internal/agentstore"
	"github.com/srjn45/warden/internal/fastbrain"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/srjn45/warden/internal/lifecycle"
	"github.com/srjn45/warden/internal/store"
	"github.com/stretchr/testify/require"
)

func TestCreatePRPushesThenOpensAndRecords(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &agentstore.Agent{
		ID: "A-1", Workdir: "/repo/.worktrees/A-1", Subject: "Add the widget", Status: store.StatusWorking,
	})
	fl := &fakeLife{
		gitPushResult: lifecycle.PushResult{Branch: "A-1", Pushed: true},
		prResult:      lifecycle.PRResult{Branch: "A-1", Base: "main", URL: "https://github.com/o/r/pull/7", Created: true},
	}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/api/v1/sessions/A-1/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusOK, resp.StatusCode)

	require.Equal(t, "/repo/.worktrees/A-1", fl.gitPushDir, "branch is pushed before the PR")
	require.Equal(t, "/repo/.worktrees/A-1", fl.prDir, "PR is opened from the agent's own worktree")
	require.Equal(t, "Add the widget", fl.prTitle, "title comes from the agent subject")
	require.Contains(t, fl.prBody, "Generated by", "body is the markdown digest")

	var got lifecycle.PRResult
	require.NoError(t, json.NewDecoder(resp.Body).Decode(&got))
	require.True(t, got.Created)
	require.Equal(t, "https://github.com/o/r/pull/7", got.URL)

	sess, _ := fs.Get(context.Background(), "A-1")
	require.NotEmpty(t, sess.Events)
	require.Equal(t, "pr", sess.Events[len(sess.Events)-1].Type)
}

func TestCreatePRHonoursBase(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &agentstore.Agent{ID: "A-1", Workdir: "/wt", Status: store.StatusWorking})
	fl := &fakeLife{prResult: lifecycle.PRResult{Created: true, URL: "u"}}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()

	body, _ := json.Marshal(map[string]string{"base": "develop"})
	resp, err := http.Post(ts.URL+"/api/v1/sessions/A-1/create-pr", "application/json", bytes.NewReader(body))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusOK, resp.StatusCode)
	require.Equal(t, "develop", fl.prBase)
}

func TestCreatePRUnknownSessionIs404(t *testing.T) {
	ts := lifeServer(t, newFakeStore(), &fakeLife{})
	defer ts.Close()
	resp, err := http.Post(ts.URL+"/api/v1/sessions/ghost/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusNotFound, resp.StatusCode)
}

func TestCreatePRNoWorkdirIsConflict(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &agentstore.Agent{ID: "A-1", Status: store.StatusWorking})
	ts := lifeServer(t, fs, &fakeLife{})
	defer ts.Close()
	resp, err := http.Post(ts.URL+"/api/v1/sessions/A-1/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusConflict, resp.StatusCode)
}

func TestCreatePRPushFailureIsConflictAndSkipsPR(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &agentstore.Agent{ID: "A-1", Workdir: "/wt", Status: store.StatusWorking})
	fl := &fakeLife{gitPushErr: errors.New("refusing to push protected branch \"main\"")}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()
	resp, err := http.Post(ts.URL+"/api/v1/sessions/A-1/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusConflict, resp.StatusCode)
	require.Empty(t, fl.prDir, "a failed push must not reach gh pr create")
}

// fakePRBrain is a scripted fastbrain.Engine: it records each request and
// replies per tier (nil entry ⇒ a timeout response).
type fakePRBrain struct {
	fastbrain.Engine
	replies map[fastbrain.Tier]string
	calls   []fastbrain.Tier
	err     error
}

func (f *fakePRBrain) Decide(_ context.Context, req fastbrain.Request) (fastbrain.Response, error) {
	f.calls = append(f.calls, req.Tier)
	if f.err != nil {
		return fastbrain.Response{}, f.err
	}
	raw, ok := f.replies[req.Tier]
	if !ok {
		return fastbrain.Response{Kind: req.Kind, Tier: req.Tier, Status: fastbrain.StatusTimeout}, nil
	}
	return fastbrain.Response{Kind: req.Kind, Tier: req.Tier, Status: fastbrain.StatusOK,
		Output: fastbrain.Output{Parsed: json.RawMessage(raw)}}, nil
}

func prBrainServer(t *testing.T, fb fastbrain.Engine) (*httptest.Server, *fakeLife) {
	t.Helper()
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &agentstore.Agent{
		ID: "A-1", Workdir: "/wt", Subject: "Add the widget", Status: store.StatusWorking,
	})
	fl := &fakeLife{prResult: lifecycle.PRResult{Created: true, URL: "u"},
		prStat: " a.go | 2 +-", prCommits: "feat: add widget"}
	srv := &Server{store: fs, life: fl, fastBrain: fb}
	ts := httptest.NewServer(srv.router())
	t.Cleanup(ts.Close)
	return ts, fl
}

func postCreatePR(t *testing.T, ts *httptest.Server, body string) {
	t.Helper()
	resp, err := http.Post(ts.URL+"/api/v1/sessions/A-1/create-pr", "application/json", strings.NewReader(body))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusOK, resp.StatusCode)
}

const draftReply = `{"title":"feat(widget): add the widget","body":"## What changed\n- widget\n\n## Why\nneeded"}`

func TestCreatePRUsesFastBrainDraftAndKeepsFooter(t *testing.T) {
	fb := &fakePRBrain{replies: map[fastbrain.Tier]string{fastbrain.TierFast: draftReply}}
	ts, fl := prBrainServer(t, fb)
	postCreatePR(t, ts, `{}`)
	require.Equal(t, "feat(widget): add the widget", fl.prTitle)
	require.Contains(t, fl.prBody, "## Why")
	require.Contains(t, fl.prBody, "Generated by a [warden]", "attribution footer is preserved")
	require.Equal(t, []fastbrain.Tier{fastbrain.TierFast}, fb.calls, "fast tier suffices")
}

func TestCreatePRFallsBackToDeterministic(t *testing.T) {
	cases := map[string]*fakePRBrain{
		"timeout":      {replies: map[fastbrain.Tier]string{}},
		"empty fields": {replies: map[fastbrain.Tier]string{fastbrain.TierFast: `{"title":"","body":""}`, fastbrain.TierThinking: `{}`}},
		"engine error": {err: errors.New("boom")},
	}
	for name, fb := range cases {
		t.Run(name, func(t *testing.T) {
			ts, fl := prBrainServer(t, fb)
			postCreatePR(t, ts, `{}`)
			require.Equal(t, "Add the widget", fl.prTitle, "today's prTitle")
			require.Contains(t, fl.prBody, "Generated by", "today's digest body")
			require.NotContains(t, fl.prBody, "## Why")
		})
	}
}

func TestCreatePRThinkingTierOnlyWhenFastBodyUnusable(t *testing.T) {
	fb := &fakePRBrain{replies: map[fastbrain.Tier]string{
		fastbrain.TierFast:     `{"title":"feat: fast title"}`,
		fastbrain.TierThinking: draftReply,
	}}
	ts, fl := prBrainServer(t, fb)
	postCreatePR(t, ts, `{}`)
	require.Equal(t, []fastbrain.Tier{fastbrain.TierFast, fastbrain.TierThinking}, fb.calls)
	require.Equal(t, "feat: fast title", fl.prTitle)
	require.Contains(t, fl.prBody, "## Why")
}

func TestCreatePRExplicitTitleAndBodyWin(t *testing.T) {
	fb := &fakePRBrain{replies: map[fastbrain.Tier]string{fastbrain.TierFast: draftReply}}
	ts, fl := prBrainServer(t, fb)
	postCreatePR(t, ts, `{"title":"my title","body":"my body"}`)
	require.Equal(t, "my title", fl.prTitle)
	require.Equal(t, "my body", fl.prBody)
	require.Empty(t, fb.calls, "no model call when both are explicit")

	// Only the title explicit: the body is still drafted.
	postCreatePR(t, ts, `{"title":"my title"}`)
	require.Equal(t, "my title", fl.prTitle)
	require.Contains(t, fl.prBody, "## Why")
}

func TestCreatePRResolvesOmittedBaseLikeSync(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &agentstore.Agent{ID: "A-1", Workdir: "/wt", BaseBranch: "integ", Status: store.StatusWorking})
	_ = fs.Insert(context.Background(), &agentstore.Agent{ID: "A-2", Workdir: "/wt2", Status: store.StatusWorking})
	fl := &fakeLife{defaultBranch: "trunk", prResult: lifecycle.PRResult{Created: true, URL: "u"}}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()

	postCreatePRTo(t, ts, "A-1", `{}`)
	require.Equal(t, "integ", fl.prBase, "recorded session base")
	postCreatePRTo(t, ts, "A-2", `{}`)
	require.Equal(t, "trunk", fl.prBase, "repository default")
	postCreatePRTo(t, ts, "A-1", `{"base":"explicit"}`)
	require.Equal(t, "explicit", fl.prBase)
}

func TestCreatePRExplicitTitleBodyVerbatim(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &agentstore.Agent{ID: "A-1", Workdir: "/wt", Status: store.StatusWorking})
	fl := &fakeLife{prResult: lifecycle.PRResult{Created: true, URL: "u"}}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()
	postCreatePRTo(t, ts, "A-1", `{"title":"My title","body":"My body"}`)
	require.Equal(t, "My title", fl.prTitle)
	require.Equal(t, "My body", fl.prBody)
}

func postCreatePRTo(t *testing.T, ts *httptest.Server, id, body string) {
	t.Helper()
	resp, err := http.Post(ts.URL+"/api/v1/sessions/"+id+"/create-pr", "application/json", strings.NewReader(body))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusOK, resp.StatusCode)
}
