package daemon

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"testing"

	"github.com/srjn45/warden/internal/lifecycle"
	"github.com/srjn45/warden/internal/store"
	"github.com/stretchr/testify/require"
)

func TestCreatePRPushesThenOpensAndRecords(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &store.Session{
		ID: "A-1", Workdir: "/repo/.worktrees/A-1", Subject: "Add the widget", Status: store.StatusWorking,
	})
	fl := &fakeLife{
		gitPushResult: lifecycle.PushResult{Branch: "A-1", Pushed: true},
		prResult:      lifecycle.PRResult{Branch: "A-1", Base: "main", URL: "https://github.com/o/r/pull/7", Created: true},
	}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()

	resp, err := http.Post(ts.URL+"/sessions/A-1/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusOK, resp.StatusCode)

	require.Equal(t, "/repo/.worktrees/A-1", fl.gitPushDir, "branch is pushed before the PR")
	require.Equal(t, "/repo/.worktrees/A-1", fl.prDir, "PR is opened from the agent's own worktree")
	require.Equal(t, "Add the widget", fl.prTitle, "title comes from the agent subject")
	require.Contains(t, fl.prBody, "Generated by", "body is the markdown digest")

	var got lifecycle.PRResult
	require.NoError(t, json.NewDecoder(resp.Body).Decode(&got))
	require.True(t, got.Created)
	require.Equal(t, "https://github.com/o/r/pull/7", got.URL)

	sess, _ := fs.Get(context.Background(), "A-1")
	require.NotEmpty(t, sess.Events)
	require.Equal(t, "pr", sess.Events[len(sess.Events)-1].Type)
}

func TestCreatePRHonoursBase(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &store.Session{ID: "A-1", Workdir: "/wt", Status: store.StatusWorking})
	fl := &fakeLife{prResult: lifecycle.PRResult{Created: true, URL: "u"}}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()

	body, _ := json.Marshal(map[string]string{"base": "develop"})
	resp, err := http.Post(ts.URL+"/sessions/A-1/create-pr", "application/json", bytes.NewReader(body))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusOK, resp.StatusCode)
	require.Equal(t, "develop", fl.prBase)
}

func TestCreatePRUnknownSessionIs404(t *testing.T) {
	ts := lifeServer(t, newFakeStore(), &fakeLife{})
	defer ts.Close()
	resp, err := http.Post(ts.URL+"/sessions/ghost/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusNotFound, resp.StatusCode)
}

func TestCreatePRNoWorkdirIsConflict(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &store.Session{ID: "A-1", Status: store.StatusWorking})
	ts := lifeServer(t, fs, &fakeLife{})
	defer ts.Close()
	resp, err := http.Post(ts.URL+"/sessions/A-1/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusConflict, resp.StatusCode)
}

func TestCreatePRPushFailureIsConflictAndSkipsPR(t *testing.T) {
	fs := newFakeStore()
	_ = fs.Insert(context.Background(), &store.Session{ID: "A-1", Workdir: "/wt", Status: store.StatusWorking})
	fl := &fakeLife{gitPushErr: errors.New("refusing to push protected branch \"main\"")}
	ts := lifeServer(t, fs, fl)
	defer ts.Close()
	resp, err := http.Post(ts.URL+"/sessions/A-1/create-pr", "application/json", strings.NewReader(`{}`))
	require.NoError(t, err)
	defer resp.Body.Close()
	require.Equal(t, http.StatusConflict, resp.StatusCode)
	require.Empty(t, fl.prDir, "a failed push must not reach gh pr create")
}
